[package]
name = "hlwrld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmc = "0.4.0"
dotenv = "0.15.0"
mac-notification-sys = "0.6"

